name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Postman CLI
        run: |
          npm install -g postman

      - name: Run Postman Collection
        run: |
          mkdir -p results
          postman collection run tests/reqres_api_postman_collection_with_tests.postman_collection.json \
            --reporters cli,json \
            --reporter-json-export results/postman-report.json

      - name: Run CSV Extraction and Validation
        run: |
          node extract-and-validate.js

      - name: Upload Results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: results/