name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install json2csv

      - name: Install Postman CLI
        run: npm install -g postman-cli

      - name: Run Postman Collection
        run: |
          mkdir -p results
          postman collection run 
tests/reqres_api_postman_collection_with_tests.postman_collection.json \
            --reporters cli,json \
            --reporter-json-export results/postman-report.json

      - name: Extract and validate CSV
        run: node extract-and-validate.js

      - name: Upload results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: results/
