name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Postman CLI
        run: npm install -g postman-cli

      - name: Install dependencies
        run: npm install json2csv

      - name: Run Postman Collection
        run: |
          mkdir -p results
          postman collection run tests/reqres_api_postman_collection_with_tests.postman_collection.json \
            --reporters cli,json \
            --reporter-json-export results/postman-report.json

      - name: Extract & Validate CSV
        run: node extract-and-validate.js

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: results/